### ISSUE TITLE
Fatal error while creating

### ISSUE THREAD

**Issue by yani66** [matstroeng/doma#32]
Hi,
I tried to set up DOMA. I used the webhosting service bplaced (freestyle) as webserver.
The MySQL server is working and the php scripts can add tables if they want. 

if I go on the index.php in Firefox (chrome based browser don't show the error), I get the error of a missing settings table
![image](https://github.com/matstroeng/doma/assets/59028071/ae493edc-ce3e-417b-b572-1534ddedb9f9)

When creating a settings table manually
![image](https://github.com/matstroeng/doma/assets/59028071/565ba682-3d50-4aad-bb20-7951ddb37192)
it creates a maps table when reloading the page, but also gives back an error.
![image](https://github.com/matstroeng/doma/assets/59028071/e9483107-428c-4a1e-a654-09503fcc15bc)
And after another refresh the error changes to maps table already existing, because it created a maps table by itself.
![image](https://github.com/matstroeng/doma/assets/59028071/b7182963-18d7-4f30-bffa-eba2089bcb4f)

**Things I already did**
- I checked the php version (8.1.13)
- I reinstalled the files from the zip
- Tried the older DOMA version (3.0.9)

Thanks in advance
Yannis

**Comment by fredricj** [comment]
This is due to php 8.1 changing the default error handling for mysqli to use exception instead of the developer having to explicitly looks for the issues. https://www.php.net/manual/en/migration81.incompatible.php :
"The default error handling mode has been changed from "silent" to "exceptions" See the [MySQLi reporting mode](https://www.php.net/manual/en/mysqli-driver.report-mode.php) page for more details on what this entails, and how to explicitly set this attribute. To restore the previous behaviour use: mysqli_report(MYSQLI_REPORT_OFF);"

**Comment by yani66** [comment]
This only changes that I no longer can see an error, but not that I can access the start page or it creating tables in the database.

**Comment by fredricj** [comment]
You need to remove the partially created database tables and browser cookies before you attempt to start access again. Otherwise it doesn't recognize it needs to create the tables.

**Comment by yani66** [comment]
There are no tables in the database.
![image](https://github.com/matstroeng/doma/assets/59028071/7457bc7c-ed74-4437-8268-6577d02b262b)
And clearing the cookies also doesn't change anything.

**Comment by bjugan** [comment]
Hi,

Try to change this line

https://github.com/matstroeng/doma/blob/fb5ede58d080892535e1b3aaca7806461efe29a0/src/include/data_access.php#L767

to

```
if($rs instanceof mysqli_result && $r = @mysqli_fetch_assoc($rs))
```

and this line
https://github.com/matstroeng/doma/blob/fb5ede58d080892535e1b3aaca7806461efe29a0/src/include/data_access.php#L784

to

```
try {
	$result = @mysqli_query($GLOBALS["dbCon"], $sql);
} catch (mysqli_sql_exception $e) {
	$result = false;
}
```

This should create the tables for you and hopefully not cause you any other problems. If you run into other problems, you can revert the file changes because they are only needed to create the tables.

**Comment by yani66** [comment]
It worked!
Thank you for your help.
